# Generated by Django 4.0.5 on 2023-01-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PupilPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Pupils',
        ),
    ]
