# Generated by Django 4.0.5 on 2023-01-19 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platformApp', '0002_pupilprefs_delete_pupils'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SimpleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('corrent_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformApp.simpleanswer')),
            ],
        ),
    ]
