# Generated by Django 4.0.5 on 2023-02-03 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platformApp', '0004_rename_corrent_answer_simplequestion_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test2Relations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformApp.measure')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformApp.simplequestion')),
            ],
        ),
    ]
