# Generated by Django 3.2.17 on 2023-05-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformApp', '0007_theory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tests',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
